//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitaiskayaKuhnya.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int id { get; set; }
        public Nullable<int> idTypeDish { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> ProductionCost { get; set; }
        public Nullable<bool> StoplistStatus { get; set; }
    
        public virtual TypeDish TypeDish { get; set; }
    }
}
